---
title: "Mandarin Implicatures"
author: "Jie Ren, Peng Zhou, Mike Frank"
date: "3/7/2018"
output: html_document
---

# Preprocessing

```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)
library(readxl)
library(langcog)
library(ggthemes)

# note, have to remove the last sheet, which is empty
all_d <- excel_sheets("data/Data_Anonymous.xlsx") %>%
  map_df(function(x) {
    d <- read_excel("data/Data_Anonymous.xlsx", sheet = x) %>%
      mutate_all(as.character)
    d$sheet <- x
    return(d)
  })
```


Clean up data. 

```{r}
d_raw <- all_d %>%
  select(-target, -contrast, -others, -`numeral exact reading`, 
         -`numeral non-exact reading`, -X__1, -X__2, -`numeral others`, 
         -`scalar others`, -`scalar contrast`, -`scalar target`) %>%
  mutate(sheet = case_when(
    sheet == " CHILD 4 you" ~ "CHILD 4 you",
    sheet == " CHILD 4 youxie" ~ "CHILD 4 youxie",
    sheet == "ADULT you" ~ "ADULT NA you", 
    sheet == "ADULT youxie" ~ "ADULT NA youxie", 
    sheet == "ADULT zhuang-le" ~ "ADULT NA zhuang-le",
    TRUE ~ sheet)) %>% 
  separate(sheet, sep = " ", into = c("group","age_years","quantifier")) %>%
  gather(trial, response, starts_with("Trial")) %>%
  mutate(age_years = as.numeric(age_years), 
         trial = as.numeric(str_replace(trial, "Trial", "")),
         response = as.numeric(response))
```

Merge in trial structure.

```{r}
design <- read_csv("data/design.csv")
d <- d_raw %>%
  left_join(design) %>%
  mutate(age_fct = factor(ifelse(is.na(age_years), "adult", age_years)))
```

Now figure out what the selected choice was. 

```{r}
d %<>%
  mutate(selected = case_when(response == 1 ~ pos_1,
                              response == 2 ~ pos_2,
                              response == 3 ~ pos_3), 
         correct = case_when(selected == "Target" ~ TRUE, 
                             trial_type == "Numeral" & selected == "Exact" & version == "V1" ~ TRUE, 
                             trial_type == "Numeral" & is.na(selected) & version == "V2" ~ TRUE, 
                             TRUE ~ FALSE))

```

# Analysis

```{r}
ms <- d %>%
  group_by(group, age_fct, trial_type, quantifier_gloss, SubjID) %>%
  summarise(correct = mean(correct)) %>%
  multi_boot_standard(col = "correct")

ggplot(ms, aes(x = age_fct, y = mean, col = trial_type)) +
  geom_line(aes(group = trial_type)) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .2)) + 
  facet_wrap(~quantifier_gloss) +
  ylim(c(0,1)) + 
  theme_few() + 
  scale_color_ptol()
```

